apiVersion: v1
kind: Pod
metadata:
  name: monitor-pod
  labels:
    app: portainer
spec:
  containers:
    - name: nginx-proxy-manager
      image: jc21/nginx-proxy-manager:latest
      ports:
        - containerPort: 80
        - containerPort: 81
      volumeMounts:
        - name: nginx-proxy-manager-data
          mountPath: /data
        - name: podmansock
          mountPath: /var/run/docker.sock
    - name: uptime-kuma
      image: louislam/uptime-kuma:1
      ports:
        - containerPort: 3001
      env:
        - name: VIRTUAL_HOST
          value: "podkuma1.uwb.edu"
        - name: VIRTUAL_PORT
          value: "3001"
      volumeMounts:
        - name: uptime-kuma-data
          mountPath: /data
        - name: podmansock
          mountPath: /var/run/docker.sock
    - name: portainer
      image: portainer/portainer-ce:latest
      ports:
        - containerPort: 9000
      env:
        - name: VIRTUAL_HOST
          value: "monitorpod.uwb.edu"
        - name: VIRTUAL_PORT
          value: "9000"
      volumeMounts:
        - name: portainer-data
          mountPath: /data
        - name: podmansock
          mountPath: /var/run/docker.sock
        - name: dockervols
          mountPath: /var/lib/docker/volumes          
    - name: portainer-agent
      image: portainer/agent
      ports:
        - containerPort: 9001
      securityContext:
        privileged: true
      volumeMounts:
        - name: podmansock
          mountPath: /var/run/docker.sock
        - name: dockervols
          mountPath: /var/lib/docker/volumes

  volumes:
    - name: nginx-proxy-manager-data
      hostPath:
        path: /home/admin/monitorpod/data/nginx-proxy-manager-data
        type: DirectoryOrCreate
    - name: uptime-kuma-data
      hostPath:
        path: /home/admin/monitorpod/data/uptime-kuma-data
        type: DirectoryOrCreate
    - name: podmansock
      hostPath:
        path: /run/podman/podman.sock
        type: File
    - name: portainer-data
      hostPath:
        path: /home/admin/monitorpod/data/portainer-data
        type: DirectoryOrCreate
    - name: dockervols
      hostPath:
        path: /home/admin/monitorpod/data/vols
        type: DirectoryOrCreate